name: Test

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          show-progress: false

      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: false

      - name: Build
        run: bundle exec middleman build
